server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO