server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  authorization:
    server:
      clientId: 'articles-client'
      clientSecret: '{noop}secret'
      authenticationRedirectUri: 'http://127.0.0.1:8080/login/oauth2/code/articles-client'
      successRedirectUri: 'http://127.0.0.1:8080/authorized'
      scope: 'articles.read'

logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO