### oauth-authorization-server와 관련된 API path 리스트를 가져오는 API
###
GET http://localhost:8081/users/me
Authorization: Bearrer eyJraWQiOiJmNmM5ZmFlZC01MWJiLTQ5ZGEtODk2YS04MzdiMTk2OTc3MWIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnQiLCJhdWQiOiJjbGllbnQiLCJuYmYiOjE2ODA0NTc5MDIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTA5MCIsImV4cCI6MTY4MDQ1ODIwMiwiaWF0IjoxNjgwNDU3OTAyfQ.QY7sPeKeQDToqLADwwkBihGxY4WLJfbWwa4Hdb4zwnK03HnMSfUxorALUadr9FLE4lVvGgX6DJktCEYOIc54EtVDJ0_B67Fk-EkpXPw1vZM87O-MFBNe8sg9gSfQG2djRA4SNevXOCe7VGkW2QHFarRvXS64gFPjK1jqNuS5zAAyZOj_y8dPYj6J1vMSM-KdV7nktXoHRibrkAeLrADMfzirDGuA869notkZkAIc5NaL2ksOydMuFW2G7Eyg2BmTyTC7mrLQG08xBLqiZsfPJkztz3TOYv2iPCuKZr651WLfR45ZlTRJAFHAiVosDF51GxHnoAqSNmrzVUBcjQnStg
